[package]
name = "cloxrs"
version = "1.0.0"
authors = ["Ellie Ang. <git@angm.xyz>"]
edition = "2018"

[dependencies]
plain_enum = "0.7.0"
enum-methods = "0.0.8"
smol_str = "0.1.17"
either = "1.6.1"
rustc-hash = "1.1.0"
smallvec = "1.6.1"
string-interner = "0.12.1"
